title: Tony Zhang
description: Detail oriented mathematician and statistician with a focus on machine learning seeking to utilize my skills and services in a technologically advanced organization to contribute to Data Scientist team. 

show_downloads: true
theme: jekyll-theme-minimal
